### ISSUE TITLE
How to get map？

### ISSUE THREAD

**Issue by lwFlyFish** [larryli/u8g2_wqy#2]
How to convert the Chinese characters in the TXT document into a MAP file?
How to convert TTF font to BDF?
thank you

**Comment by larryli** [comment]
Q1: https://github.com/larryli/u8g2_wqy/wiki/CustomFont#%E5%B0%86-txt-%E8%BD%AC%E6%8D%A2%E6%88%90-bdfconv-%E6%89%80%E9%9C%80%E8%A6%81%E7%9A%84-map

Q2: No way.
