### ISSUE TITLE
您好，您的wiki里面的一些目录我没有找到

### ISSUE THREAD

**Issue by dtboy1995** [larryli/u8g2_wqy#4]
您好，您的wiki里面的一些目录我没有找到，以至于接下来没能继续跟着教程做下去，我是通过 加载库->管理库 安装的u8g2，您的教程能再详细一些吗，我想照着做一遍，打扰了，谢谢

**Comment by larryli** [comment]
@dtboy1995 描述具体一点，不清楚你问的什么。

**Comment by dtboy1995** [comment]
@larryli 谢谢您的回答

我问的是您 WIKI中的`CustomFont`的这块教程

跟着您的教程做到bdfconv 这块就做不下去了，这块您写到需要修改一个c文件的源码，但是那个文件我没有找到，我是小白，希望您谅解，因为没有找到这个相关的东西，所以来请教一下您，我的u8g2是在那个库中搜索直接添加的。

**Comment by larryli** [comment]
https://github.com/olikraus/u8g2/tree/master/tools/font/bdfconv
