### ISSUE TITLE
关于iconv工具

### ISSUE THREAD

**Issue by SuDaming** [larryli/u8g2_wqy#5]
您好！
请教一下，我在使用iconv工具时Linux提示不支持c99编码，如下：
cat str.txt | iconv -f utf-8 -t c99  | sed 's/\\u\([0-9a-f]\{4\}\)/\$\1,\n/g' | sort | uniq | sed '/^$/d' | tr '/a-f/' '/A-F/' >> my.map

iconv: conversion to `c99' is not supported
Try `iconv --help' or `iconv --usage' for more information.

请问您是如何解决的？

**Comment by larryli** [comment]
http://git.savannah.gnu.org/cgit/libiconv.git/commit/?id=ed9ef0915d2f10de5792cf24e974572ebc464ce0

升级到 2009 年以后版本的 iconv。

**Comment by SuDaming** [comment]
非常感谢您，按照您的方法，问题已经解决

**Comment by imxood** [comment]
> 非常感谢您，按照您的方法，问题已经解决

你这个是怎么解决的呀, 大概是2002年的iconv, 你是编译出这个版本的iconv吗？但这也不太好编译, 我下载了gcc4.9, 也没能编译成功...可以讲一下方法吗？。。。

**Comment by imxood** [comment]
@SuDaming

**Comment by imxood** [comment]
@SuDaming

**Comment by imxood** [comment]
@SuDaming 最后还是写了一段python代码解决这个问题

···
import re
import os

chineses = '''主菜单
菜单一
菜单二
菜单三
确定
取消
返回
'''

chineses = re.sub(r'\s', '', chineses).encode('unicode_escape').decode()
chineses = re.sub(r'\\u([0-9a-f]{4})', r'$\1,' + os.linesep, chineses).strip().upper()
map_content = '32-128,' + os.linesep + chineses
print(map_content)
with open('myfont.map', 'w') as f:
    f.write(map_content)
···

**Comment by SuDaming** [comment]
@imxood 抱歉，回的晚了，我记得当时我就是升级了iconv之后就解决了的，具体怎么升级的记不太清了。时间太久了，不记得当时做这个项目的具体情况了。你能通过python解决也可以的，只是我不懂python，当时没想到可以用python解决。
